-- DROP TABLE CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER (10) NOT NULL,
    CPF VARCHAR2 (11) NOT NULL,
    NOME VARCHAR2 (30) NOT NULL
  );
ALTER TABLE CLIENTE ADD CONSTRAINT CLI_PK PRIMARY KEY ( ID_CLIENTE ) ;
ALTER TABLE CLIENTE ADD CONSTRAINT CLI_UK_CPF UNIQUE ( CPF );

CREATE SEQUENCE CLIENTE_SEQ;

CREATE TABLE FILME(
    ID_FILME NUMBER(10) NOT NULL,
    TITULO VARCHAR2(30) NOT NULL,
    VALOR NUMBER(12,2) NOT NULL,
    PRAZO NUMBER(5) NOT NULL,
    CATEGORIA VARCHAR2(30) NOT NULL
);
ALTER TABLE FILME ADD CONSTRAINT FILME_PK PRIMARY KEY (ID_FILME);

CREATE TABLE FITA(
    ID_FILME NUMBER(10) NOT NULL,
    ID_FITA NUMBER(10) NOT NULL,
    LOCADO BOOLEAN NOT NULL
);
ALTER TABLE FITA ADD CONSTRAINT FITA_PK PRIMARY KEY(ID_FITA);
ALTER TABLE FITA ADD CONSTRAINT FILME_FK FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME)
