-- DROP TABLE CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER (10) NOT NULL,
    CPF VARCHAR2 (11) NOT NULL,
    NOME VARCHAR2 (30) NOT NULL
  );
ALTER TABLE CLIENTE ADD CONSTRAINT CLI_PK PRIMARY KEY ( ID_CLIENTE ) ;
ALTER TABLE CLIENTE ADD CONSTRAINT CLI_UK_CPF UNIQUE ( CPF );

CREATE SEQUENCE CLIENTE_SEQ;

CREATE TABLE FILME(
    ID_FILME NUMBER(10) NOT NULL,
    TITULO VARCHAR2(30) NOT NULL,
    VALOR NUMBER(12,2) NOT NULL,
    PRAZO NUMBER(5) NOT NULL,
    CATEGORIA VARCHAR2(30) NOT NULL
);
ALTER TABLE FILME ADD CONSTRAINT FILME_PK PRIMARY KEY (ID_FILME);

CREATE SEQUENCE FILME_SEQ;

CREATE TABLE FITA(
    ID_FILME NUMBER(10) NOT NULL,
    ID_FITA NUMBER(10) NOT NULL,
    LOCADO NUMBER(1) NOT NULL
);

CREATE SEQUENCE FITA_SEQ;

ALTER TABLE FITA ADD CONSTRAINT FITA_PK PRIMARY KEY(ID_FITA);
ALTER TABLE FITA ADD CONSTRAINT FILME_FK FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME);

CREATE TABLE PEDIDO(
    ID_PEDIDO NUMBER(10) NOT NULL,
    ID_CLIENTE NUMBER(10) NOT NULL,
    STATUS_PEDIDO VARCHAR2(30) NOT NULL,
    VALOR NUMBER(12,2) NOT NULL
);

ALTER TABLE PEDIDO ADD CONSTRAINT PEDI_PK PRIMARY KEY ( ID_PEDIDO ) ;
ALTER TABLE PEDIDO ADD CONSTRAINT CLI_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);

CREATE SEQUENCE PEDIDO_SEQ;

CREATE TABLE LOCACAO(
    ID_LOCACAO NUMBER(10) NOT NULL,
    ID_PEDIDO NUMBER(10) NOT NULL,
    ID_FITA NUMBER(10) NOT NULL,
    PRAZO DATE NOT NULL,
    STATUS_LOCACAO VARCHAR2(30) NOT NULL
);

CREATE SEQUENCE LOCACAO_SEQ;

ALTER TABLE LOCACAO ADD CONSTRAINT ID_LOCACAO PRIMARY KEY( ID_LOCACAO );
ALTER TABLE LOCACAO ADD CONSTRAINT PEDI_FK FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO);
ALTER TABLE LOCACAO ADD CONSTRAINT FITA_FK FOREIGN KEY(ID_FITA) REFERENCES FITA(ID_FITA);

