-- exercicio 1
Select PR.IDPRODUTO, PR.NOME, PR.SITUACAO
FROM PRODUTO PR
WHERE PR.IDPRODUTO 
NOT IN (
  SELECT DISTINCT PI.IDPRODUTO
  FROM PEDIDOITEM PI
  inner join PEDIDO P ON PI.IDPEDIDO=P.IDPEDIDO 
  WHERE P.DATAPEDIDO>=add_months(sysdate,-6)
);

CREATE VIEW ProdutoSemVendaAteSeisMeses AS (
  Select PR.IDPRODUTO, PR.NOME
  FROM PRODUTO PR
  WHERE PR.IDPRODUTO 
  NOT IN (
    SELECT DISTINCT PI.IDPRODUTO
    FROM PEDIDOITEM PI
    inner join PEDIDO P ON PI.IDPEDIDO=P.IDPEDIDO 
    WHERE P.DATAPEDIDO>=add_months(sysdate,-6)
  )
)

--exercicio 2
UPDATE PRODUTO
SET PRODUTO.Situacao = 'I'
where Produto.IdProduto in(Select P.IDPRODUTO from ProdutoSemVendaAteSeisMeses P);
commit;

-- exercicio 3
UPDATE CLIENTE
SET SITUACAO='I'
WHERE NOT EXISTS(
Select CLI.IDCLIENTE FROM CLIENTE CLI
INNER JOIN PEDIDO P ON P.IDCLIENTE=CLI.IDCLIENTE
WHERE P.DATAPEDIDO>=add_months(sysdate,-6));


